package com.example.bpmn.controller;

import com.example.bpmn.dto.CompleteTaskRequest;
import com.example.bpmn.exception.AppException;
import com.example.bpmn.http.BaseController;
import com.example.bpmn.service.TaskService;
import com.example.bpmn.util.JsonUtil;

/**
 * Controller handling REST API requests for runtime tasks generated by process instances.
 */
public class TaskController extends BaseController {
    private final TaskService taskService;

    public TaskController(TaskService taskService) {
        this.taskService = taskService;

        get("/api/tasks", ctx -> {
            String status = ctx.query("status");
            boolean onlyMine = "true".equalsIgnoreCase(ctx.query("mine", "false"));
            return taskService.listTasks(status, onlyMine, ctx.authUserId(), ctx.pageParam(), ctx.sizeParam());
        });
        get("/api/tasks/:id", ctx -> taskService.getTaskById(ctx.param("id")));
        post("/api/tasks/:id/claim", ctx -> taskService.claimTask(ctx.param("id"), ctx.authUserId()));
        post("/api/tasks/:id/complete", ctx -> {
            String raw = ctx.rawBody();
            CompleteTaskRequest request;
            if (raw.isBlank()) {
                request = new CompleteTaskRequest();
            } else {
                try {
                    request = JsonUtil.fromJson(raw, CompleteTaskRequest.class);
                } catch (RuntimeException e) {
                    throw new AppException("Invalid JSON request body", 400);
                }
            }
            return taskService.completeTask(ctx.param("id"), ctx.authUserId(), ctx.authRole(), request);
        });
    }
}
